//ob_splash
//————————————————————————————————————————————————————————————————————————————————————————————————————
depth=-1000;
//
text_timer_max=50;
text_timer=text_timer_max;
text_rel_y=0;
text_potential_y=text_rel_y;
text_color=c_white;