function sc_keyname(argument0) {
/// @param key
//————————————————————————————————————————————————————————————————————————————————————————————————————
switch (argument0) {
	case vk_up: return("Up"); break;
	case vk_down: return("Down"); break;
	case vk_right: return("Right"); break;
	case vk_left: return("Left"); break;
	//case vk_enter: return("Enter"); break;
	//case vk_space: return("Spacebar"); break;
	case vk_add: return("Add"); break;
	case vk_subtract: return("Subtract"); break;
	//case vk_backspace: return("Backspace"); break;
	case vk_lcontrol: return("Ctrl"); break;
	//case vk_alt: return("Alt"); break;
	case vk_shift: return("Shift"); break;
	case vk_decimal: return("Decimal"); break;
	case vk_delete: return("Delete"); break;
	case vk_divide: return("Divide"); break;
	//case vk_escape: return("Escape"); break;
	case vk_end: return("End"); break;
	case vk_f1: return("F1"); break;
	case vk_f2: return("F2"); break;
	case vk_f3: return("F3"); break;
	case vk_f4: return("F4"); break;
	case vk_f5: return("F5"); break;
	case vk_f6: return("F6"); break;
	case vk_f7: return("F7"); break;
	case vk_f8: return("F8"); break;
	case vk_f9: return("F9"); break;
	//case vk_f10: return("F10"); break; //reservado para funcion 'debug notes'
	//case vk_f11: return("F11"); break;
	//case vk_f12: return("F12"); break;
	case vk_numpad0: return("Numpad 0"); break;
	case vk_numpad1: return("Numpad 1"); break;
	case vk_numpad2: return("Numpad 2"); break;
	case vk_numpad3: return("Numpad 3"); break;
	case vk_numpad4: return("Numpad 4"); break;
	case vk_numpad5: return("Numpad 5"); break;
	case vk_numpad6: return("Numpad 6"); break;
	case vk_numpad7: return("Numpad 7"); break;
	case vk_numpad8: return("Numpad 8"); break;
	case vk_numpad9: return("Numpad 9"); break;
	case vk_home: return("Home"); break;
	case vk_insert: return("Insert"); break;
	case vk_multiply: return("Multiply"); break;
	case vk_pagedown: return("Page Down"); break;
	case vk_pageup: return("Page Up"); break;
	case vk_printscreen: return("Print Screen"); break;
	case vk_tab: return("Tab"); break;
	case 144: return("Numlock"); break;
	case 145: return("Scrlock"); break;
	case 186: return(";"); break;
	case 187: return("="); break;
	case 189: return("-"); break;
	case 191: return("/"); break;
	case 192: return("`"); break;
	case 219: return("["); break;
	case 220: return("\\"); break;
	case 221: return("]"); break;
	case 188: return(","); break;
	case 190: return("."); break;
	case 222: return("'"); break;
	case 19: return("Pause/Break"); break;
	case 20: return("Capslock"); break;
	case ord("A"): return("A"); break;
	case ord("B"): return("B"); break;
	case ord("C"): return("C"); break;
	case ord("D"): return("D"); break;
	case ord("E"): return("E"); break;
	case ord("F"): return("F"); break;
	case ord("G"): return("G"); break;
	case ord("H"): return("H"); break;
	case ord("I"): return("I"); break;
	case ord("J"): return("J"); break;
	case ord("K"): return("K"); break;
	case ord("L"): return("L"); break;
	case ord("M"): return("M"); break;
	case ord("N"): return("N"); break;
	case ord("O"): return("O"); break;
	case ord("P"): return("P"); break;
	case ord("Q"): return("Q"); break;
	case ord("R"): return("R"); break;
	case ord("S"): return("S"); break;
	case ord("T"): return("T"); break;
	case ord("U"): return("U"); break;
	case ord("V"): return("V"); break;
	case ord("W"): return("W"); break;
	case ord("X"): return("X"); break;
	case ord("Y"): return("Y"); break;
	case ord("Z"): return("Z"); break;
	//case ord("1"): return("1"); break;
	//case ord("2"): return("2"); break;
	//case ord("3"): return("3"); break;
	case ord("4"): return("4"); break;
	case ord("5"): return("5"); break;
	case ord("6"): return("6"); break;
	case ord("7"): return("7"); break;
	case ord("8"): return("8"); break;
	case ord("9"): return("9"); break;
	case ord("0"): return("0"); break;
	//
	default: return("empty");
}
//————————————————————————————————————————————————————————————————————————————————————————————————————
}