randomize(); //random seed
game_name="The Crystal Road";
game_version="v0.0.0.4";
window_set_caption(game_name + " " + string(game_version));
//————————————————————————————————————————————————————————————————————————————————————————————————————
depth=-1000;
//
camera_set_view_pos(view_camera[0],x,y);
camera_set_view_size(view_camera[0],512,288);
camera_set_view_target(view_camera[0],ob_control);
camera_set_view_border(view_camera[0],99999,99999);
camera_set_view_speed(view_camera[0],-1,-1);
cam_x=camera_get_view_x(view_camera[0]);
cam_y=camera_get_view_y(view_camera[0]);
cam_w=camera_get_view_width(view_camera[0]);
cam_h=camera_get_view_height(view_camera[0]);
surface_resize(application_surface,cam_w*2,cam_h*2);
//
display_reset(0,true);
window_set_fullscreen(false);
//————————————————————————————————————————————————————————————————————————————————————————————————————
global.sound_level=10;
global.music_level=10;
//————————————————————————————————————————————————————————————————————————————————————————————————————
instance_create_layer(16,16,"instances",ob_card);
instance_create_layer(80,16,"instances",ob_card);
instance_create_layer(144,16,"instances",ob_card);
instance_create_layer(208,16,"instances",ob_card);
instance_create_layer(272,16,"instances",ob_card);
instance_create_layer(336,16,"instances",ob_card);
instance_create_layer(400,16,"instances",ob_card);
instance_create_layer(16,103,"instances",ob_card);
instance_create_layer(80,103,"instances",ob_card);
instance_create_layer(144,103,"instances",ob_card);
instance_create_layer(208,103,"instances",ob_card);
instance_create_layer(272,103,"instances",ob_card);
instance_create_layer(336,103,"instances",ob_card);
instance_create_layer(400,103,"instances",ob_card);
instance_create_layer(16,190,"instances",ob_card);
instance_create_layer(80,190,"instances",ob_card);
instance_create_layer(144,190,"instances",ob_card);
instance_create_layer(208,190,"instances",ob_card);
instance_create_layer(272,190,"instances",ob_card);
instance_create_layer(336,190,"instances",ob_card);
instance_create_layer(400,190,"instances",ob_card);
//————————————————————————————————————————————————————————————————————————————————————————————————————
tooltip_text="";
//
event_active=false;
reset_objects=false;
screen_transition=false;
//
fade_black=0;
textbox_active=false;
text_string="";
text_show="";
text_charnum=1;
text_timer=0;
text_timermax=1;
text_next=false;