depth=300;
//
occupy_id=-1;
trash=false;
//
berries_total=0;
berries_total_type[0]=0;
berries_total_type[1]=0;
berries_total_type[2]=0;
berries_total_type[3]=0;
//
card_bonus_atk=0;
card_bonus_def=0;
card_penalty_atk=0;
card_penalty_def=0;
